INSERT INTO public.URUN( ID, ADI, FIYAT, KAYIT_TARIHI, ID_KATEGORI) VALUES (	1	,'Mavi Elbise',	200	, now(), 	4);
INSERT INTO public.URUN( ID, ADI, FIYAT, KAYIT_TARIHI, ID_KATEGORI) VALUES (	2	,'Kırmızı Elbise',	300	, now(), 	4);
INSERT INTO public.URUN( ID, ADI, FIYAT, KAYIT_TARIHI, ID_KATEGORI) VALUES (	3	,'Mavi Gömlek',	500	, now(), 	5);
INSERT INTO public.URUN( ID, ADI, FIYAT, KAYIT_TARIHI, ID_KATEGORI) VALUES (	4	,'Sarı Gömlek',	450	, now(), 	5);
INSERT INTO public.URUN( ID, ADI, FIYAT, KAYIT_TARIHI, ID_KATEGORI) VALUES (	5	,'HP ',	15000	, now(), 	7);
INSERT INTO public.URUN( ID, ADI, FIYAT, KAYIT_TARIHI, ID_KATEGORI) VALUES (	6	,'MSI',	20000	, now(), 	7);
INSERT INTO public.URUN( ID, ADI, FIYAT, KAYIT_TARIHI, ID_KATEGORI) VALUES (	7	,'Orta Sehpa',	600	, now(), 	9);