# Use postgres/example user/password credentials

version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 12345

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080